name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  check_secrets:
    name: Check secrets
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME is not set"
            exit 1
          fi

          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is not set"
            exit 1
          fi

          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "SERVER_HOST is not set"
            exit 1
          fi

          if [ -z "${{ secrets.SERVER_USER }}" ]; then
            echo "SERVER_USER is not set"
            exit 1
          fi

          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "SSH_PRIVATE_KEY is not set"
            exit 1
          fi
  build:
    needs: check_secrets
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t wb .

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wb:${{ github.sha }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker rmi $(docker images -a -q)
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/wb:${{ github.sha }}
            docker stop wb
            docker rm wb
            docker run -d -p 80:80 --name wb ${{ secrets.DOCKERHUB_USERNAME }}/wb:${{ github.sha }}
